name: Docker CD

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.3
    - run: |
        go mod download
        go build -o artifact ./cmd
    - uses: actions/upload-artifact@main
      with:
        name: izharishaksa-com
        path: |
          artifact
          internal/

  Build-and-Push-Docker-Image:
    runs-on: ubuntu-latest
    needs: build
    name: Docker Build, Tag, Push

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Download built artifact
      uses: actions/download-artifact@main
      with:
        name: izharishaksa-com
    - name: Build container image
      uses: docker/build-push-action@v1
      with:
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
        registry: docker.pkg.github.com
        repository: izharishaksa/github-actions-for-packages/izharishaksa.com
        tag_with_sha: true
    - uses: actions/delete-package-versions@v2
      with: 
        package-name: 'izharishaksa.com'
        min-versions-to-keep: 2
        delete-only-pre-release-versions: "true"

