name: Docker CD

on:
  push:
  pull_request:

jobs:

  build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.3
      - run: |
          go mod download
          GOOS=darwin GOARCH=amd64 go build -o izharishaksa-com ./cmd
      - uses: actions/upload-artifact@main
        with:
          name: artifact
          path: |
            izharishaksa-com
            internal/