name: Docker CD

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.3
    - run: |
        go mod download
        go build -o artifact ./cmd
    - uses: actions/upload-artifact@main
      with:
        name: izharishaksa-com
        path: |
          artifact
          internal/

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.3
    - run: |
        go mod download
        go test ./... -v
